[app]
name = "Eanray"

[app.scene]
output_file = "output.ppm"

[app.scene.camera.defaults]
samples_per_pixel = 10
antialiasing = true
max_depth = 10
field_of_view = 90
look_from = [0, 0, 0]
look_at = [0, 0, -1]
vup = [0, 1, 0]
defocus_angle = 0
focus_distance = 10
background = [0, 0, 0]

[app.diagnostics]
enable_metrics = false
enable_stats = false